# -*- coding: utf-8 -*-
"""CNN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11ha4drnUCfb7mxM5kUtOS0vVUJ30UCSl
"""

pip install awkward

from network_lib import *

import numpy as np
import tensorflow as tf
import os

from tensorflow import keras
model = keras.models.load_model('/PATH_TO_MODEL/muon/small_cnn_model36.h5')

tracks_name = 'NAME_FILE'
file_num=7
def make_pred(tracks_name,file_num):
  """predicts accuracy of CNN model """
  list_track= []

  indir = f'/PATH_TO_CNN_IMAGES/CNN_txt_files_{file_num}/{tracks_name}/'
  track_files = [name for name in os.listdir(indir) if os.path.isfile(os.path.join(indir, name))]
  for track in track_files:
    list_track.append(np.loadtxt(indir+track, delimiter = ","))
  
  track_array = np.array(list_track) 


  track_array = tf.convert_to_tensor(track_array, dtype=tf.int64)    
  track_array = tf.expand_dims(track_array, 3)
                      
  preds = model.predict(track_array)
  print(f'False tracks {tracks_name}.............{len(preds[np.where(preds[:,1] >=0.5)])}')
  print(f'True tracks {tracks_name}............{len(preds[np.where(preds[:,0] >=0.5)])}')
  
  print(len(model.predict(track_array)), len(list_track),len(track_files))

make_pred(tracks_name,file_num)